### ISSUE TITLE
Arduino: Upload Error: bossac not found

### ISSUE THREAD

**Issue by HayWo** [bleeptrack/picoplanet#1]
Uploading a sketch to the PicoPlanet fails, because a tool called `bossac` was not found.

### How to fix this
Install the Arduino Board Manager called `Arduino SAMD Boards (32-bits ARM Cortex-M0+)`

**Comment by bleeptrack** [comment]
Hey HayWo! Oh well, that's weird! I tested on a fresh arduino install and did not encounter this problem. bossac is declared in the toolDependencies and should be installed with the bleeptrack-board package. Though seems it did not work for you.
I'll add your workaround to a Troubleshooting section.
Would you mind telling me what Arduino IDE version and OS you are running? Thanks!

**Comment by HayWo** [comment]
I'm using Arduino IDE 1.8.13 on Arch Linux. Maybe I just have a messed up installation of the IDE.
