### ISSUE TITLE
Proposal: Add information how to update Circuit Python version

### ISSUE THREAD

**Issue by Isolator70** [bleeptrack/picoplanet#11]
Some time ago I installed Circuit Python version version 6.3.0 on my Picoplanet board and I'd like to update to the latest and greatest version 7.3.3 now.
I suspect that it can be done by means of the reset contact, but I am not really sure if this right.

--> Would you be so kind to add this information?

**Comment by bleeptrack** [comment]
Hey Isolator70! That is a great suggestion, thank you a lot! With the latest commit 794ce11  I added a bullet point to the CP section that contains a description and video on how to get back to bootloader mode to update the firmware :)
