### ISSUE TITLE
Updating CircuitPython version

### ISSUE THREAD

**Issue by bergold** [bleeptrack/picoplanet#4]
Is there an easy way to get into the bootloader again? So I can drag-n-drop a new uf2 file.

**Comment by bleeptrack** [comment]
Hey bergold! Yes there is :)
To bring your board into bootloader mode, connect a wire to the GND pin on the backside and double tap the RESET pad with the other end of the wire. The PLANETBOOT drive should appear now. 

I currently only wrote about this in the Arduino section. I'll update the readme file in the Circuit Python section, too :)

**Comment by bergold** [comment]
Thanks for the quick reply! :)
